// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {workspace} from '../models';
import {runner} from '../models';
import {config} from '../models';

export function InspectWorkspace(arg1:string):Promise<workspace.Summary>;

export function ListProcesses():Promise<Array<runner.Process>>;

export function ListRecentWorkspaces():Promise<Array<config.RecentWorkspace>>;

export function OpenWorkspaceDialog():Promise<string>;

export function RunCommand(arg1:string,arg2:string):Promise<runner.Process>;

export function StopCommand(arg1:string):Promise<void>;
