// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeWorkspace(arg1) {
  return window['go']['main']['App']['AnalyzeWorkspace'](arg1);
}

export function CloseApp() {
  return window['go']['main']['App']['CloseApp']();
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function InspectWorkspace(arg1) {
  return window['go']['main']['App']['InspectWorkspace'](arg1);
}

export function ListProcesses() {
  return window['go']['main']['App']['ListProcesses']();
}

export function ListProfiles() {
  return window['go']['main']['App']['ListProfiles']();
}

export function ListRecentWorkspaces() {
  return window['go']['main']['App']['ListRecentWorkspaces']();
}

export function OpenWorkspaceDialog() {
  return window['go']['main']['App']['OpenWorkspaceDialog']();
}

export function RestartCommand(arg1) {
  return window['go']['main']['App']['RestartCommand'](arg1);
}

export function RunCommand(arg1, arg2) {
  return window['go']['main']['App']['RunCommand'](arg1, arg2);
}

export function RunProfile(arg1) {
  return window['go']['main']['App']['RunProfile'](arg1);
}

export function SaveProfile(arg1) {
  return window['go']['main']['App']['SaveProfile'](arg1);
}

export function StopCommand(arg1) {
  return window['go']['main']['App']['StopCommand'](arg1);
}
